def get_column_names():
    return ['accommodates', 'bathrooms', 'bedrooms', 'beds', 'guests_included',
       'extra_people', 'minimum_nights', 'maximum_nights', 'Heat lamps',
       'Sound system', 'Shared gym', 'Pack n Play/travel crib',
       'Balcony', 'Waterfront', 'Fire pit', 'Wine cooler',
       'Shared hot tub', 'Doorman', 'Printer', 'Shared pool',
       'Ski-in/Ski-out', 'Private gym', 'Heated towel rack',
       'Mountain view', 'Formal dining area', 'Bidet', 'Standing valet',
       'Sun loungers', 'neighbourhood_Alki',
       'neighbourhood_Arbor Heights', 'neighbourhood_Atlantic',
       'neighbourhood_Ballard', 'neighbourhood_Belltown',
       'neighbourhood_Bitter Lake', 'neighbourhood_Brighton',
       'neighbourhood_Broadview', 'neighbourhood_Bryant',
       'neighbourhood_Capitol Hill', 'neighbourhood_Cedar Park',
       'neighbourhood_Central Business District',
       'neighbourhood_Columbia City', 'neighbourhood_Crown Hill',
       'neighbourhood_Dunlap', 'neighbourhood_Eastlake',
       'neighbourhood_Fauntleroy', 'neighbourhood_First Hill',
       'neighbourhood_Fremont', 'neighbourhood_Gatewood',
       'neighbourhood_Genesee', 'neighbourhood_Georgetown',
       'neighbourhood_Green Lake', 'neighbourhood_Greenwood',
       'neighbourhood_Haller Lake', 'neighbourhood_Harrison/Denny-Blaine',
       'neighbourhood_High Point', 'neighbourhood_Highland Park',
       'neighbourhood_Holly Park', 'neighbourhood_Industrial District',
       'neighbourhood_Interbay', 'neighbourhood_International District',
       'neighbourhood_Laurelhurst', 'neighbourhood_Leschi',
       'neighbourhood_Licton Springs', 'neighbourhood_Lower Queen Anne',
       'neighbourhood_Madison Park', 'neighbourhood_Madrona',
       'neighbourhood_Magnolia', 'neighbourhood_Maple Leaf',
       'neighbourhood_Mathews Beach', 'neighbourhood_Meadowbrook',
       'neighbourhood_Minor', 'neighbourhood_Montlake',
       'neighbourhood_Mount Baker', 'neighbourhood_North Admiral',
       'neighbourhood_North Beach/Blue Ridge',
       'neighbourhood_North Beacon Hill', 'neighbourhood_North Delridge',
       'neighbourhood_Olympic Hills', 'neighbourhood_Phinney Ridge',
       'neighbourhood_Pike Place Market', 'neighbourhood_Pinehurst',
       'neighbourhood_Pioneer Square', 'neighbourhood_Portage Bay',
       'neighbourhood_Queen Anne', 'neighbourhood_Rainier Beach',
       'neighbourhood_Rainier View', 'neighbourhood_Ravenna',
       'neighbourhood_Riverview', 'neighbourhood_Roosevelt',
       'neighbourhood_Roxhill', 'neighbourhood_Seaview',
       'neighbourhood_Seward Park', 'neighbourhood_South Beacon Hill',
       'neighbourhood_South Delridge', 'neighbourhood_South Lake Union',
       'neighbourhood_South Park', 'neighbourhood_Stevens',
       'neighbourhood_The Junction', 'neighbourhood_University District',
       'neighbourhood_Victory Heights', 'neighbourhood_View Ridge',
       'neighbourhood_Wallingford', 'neighbourhood_Wedgewood',
       'neighbourhood_Westlake', 'neighbourhood_Windermere',
       'neighbourhood_Yesler Terrace', 'zipcode_98052', 'zipcode_98101',
       'zipcode_98102', 'zipcode_98103', 'zipcode_98104', 'zipcode_98105',
       'zipcode_98106', 'zipcode_98107', 'zipcode_98108', 'zipcode_98109',
       'zipcode_98110', 'zipcode_98112', 'zipcode_98115', 'zipcode_98116',
       'zipcode_98117', 'zipcode_98118', 'zipcode_98119', 'zipcode_98121',
       'zipcode_98122', 'zipcode_98125', 'zipcode_98126', 'zipcode_98133',
       'zipcode_98134', 'zipcode_98136', 'zipcode_98144', 'zipcode_98146',
       'zipcode_98155', 'zipcode_98177', 'zipcode_98178', 'zipcode_98199',
       'property_type_Aparthotel', 'property_type_Apartment',
       'property_type_Bed and breakfast', 'property_type_Boat',
       'property_type_Boutique hotel', 'property_type_Bungalow',
       'property_type_Cabin', 'property_type_Camper/RV',
       'property_type_Castle', 'property_type_Condominium',
       'property_type_Cottage', 'property_type_Earth house',
       'property_type_Farm stay', 'property_type_Guest suite',
       'property_type_Guesthouse', 'property_type_Hostel',
       'property_type_House', 'property_type_Houseboat',
       'property_type_Hut', 'property_type_In-law',
       'property_type_Lighthouse', 'property_type_Loft',
       'property_type_Other', 'property_type_Serviced apartment',
       'property_type_Tent', 'property_type_Tiny house',
       'property_type_Townhouse', 'property_type_Treehouse',
       'property_type_Villa', 'property_type_Yurt',
       'room_type_Entire home/apt', 'room_type_Private room',
       'room_type_Shared room', 'bed_type_Airbed', 'bed_type_Couch',
       'bed_type_Futon', 'bed_type_Pull-out Sofa', 'bed_type_Real Bed']